# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.
samples: "config/samples.tsv"
is_pe: True

genome:
  species: hsa
  reference_fa: "path/to/fa"
  reference_idx: "path/to/fa.fai"
  blacklist: "path/to/bed"
  macs-gsize:

params:
  # choose "narrow" or "broad" for macs2 callpeak analysis, for documentation and source code please see https://github.com/macs3-project/MACS
  peak-analysis: "broad"
  # Number of biological replicates required from a given condition for a peak to contribute to a consensus peak
  min-reps-consensus: 1
  callpeak:
    pvalue: 0.5
    qvalue: 
    keep_dup: all
    nolambda: False
    broad: True
    broad-cutoff: 0.1

  deeptools-plots:
    # when activated the plot profile and heatmap plot are generated, this involves a matrix calculation that requires a lot of working memory.
    activate: False
  lc_extrap:
    activate: True
  picard_metrics:
    activate: True
  deseq2:
    # optional to run vst transform instead of rlog
    vst: False
  peak-annotation-analysis:
    activate: True
  peak-qc:
    activate: True
  consensus-peak-analysis:
    activate: True
  # samtools view parameters:
  # if duplicates should be removed in this filtering, add "-F 0x0400" to the params
  # if for each read, you only want to retain a single (best) mapping, add "-q 1" to params
  # if you would like to restrict analysis to certain regions (e.g. excluding other "blacklisted" regions),
  # the -L option is automatically activated if a path to a blacklist of the given genome exists in "config/igenomes.yaml" or has been entered there
  samtools-view-se: "-b -F 0x004"
  samtools-view-pe: "-b -F 0x004 -G 0x009 -f 0x001"
